export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
export const WATCH_AD_REQUEST = 'WATCH_AD_REQUEST';
export const WATCH_AD_SUCCESS = 'WATCH_AD_SUCCESS';
export const WATCH_AD_FAILURE = 'WATCH_AD_FAILURE';
